title: S.Mona
description: ""
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://silbertmonaphia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: silbertmonaphia@gmail.com
twitter_username: silbertmonaphia
github_username:  silbertmonaphia

# Build settings
markdown: kramdown
toc_levels: 1..6

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# prose.io config
prose:
    rooturl: '_posts'
    siteurl: 'https://silbertmonaphia.github.io/'
